### ISSUE TITLE
s3 dp_connect issue on windows

### ISSUE THREAD

**Issue by camorosi** [amashadihossein/dpi#38]
`dp_connect.s3_board()` does not return a proper board object on windows due to `file.path(board_subdir)` removing the trailing slash in "daap/" or other referenced prefixes. 

Board will be returned from `dp_connect()`, but will not work within `dp_list()` and `dp_get()`. A workaround is to manually edit the prefix in the board object `board_object$prefix <- "daap/"`

Unclear if this issue also affects labkey or local boards

**Comment by amashadihossein** [comment]
I can reproduce the issue on windows. This is a critical issue as it prevents the basic vignette ([A minimalist example](https://amashadihossein.github.io/daapr/articles/min_wrkfl.html)) to work. 

To reproduce, run the basic vignette. The error is thrown when trying to read the input via `dp_list` on [step 4](https://amashadihossein.github.io/daapr/articles/min_wrkfl.html#step-4-build-the-data-product)
